export interface IdeaItem {
  ticker: string;
  name: string;
  price: number;
  chgPct: number;
  tag: "52W HIGH" | "MOMO" | "VOLUME SPIKE" | "PULLBACK" | "BREAKOUT";
  metrics: {
    chg1d: number;
    chg5d: number;
    chg20d: number;
    near52wHigh: boolean;
    volumeSpike: boolean;
    tradingValue: number; // billion KRW
  };
  headlines?: string[];
}

export const FOMO_IDEAS: IdeaItem[] = [
  {
    ticker: "000660",
    name: "SK Hynix",
    price: 218000,
    chgPct: 2.84,
    tag: "52W HIGH",
    metrics: { chg1d: 2.84, chg5d: 8.12, chg20d: 14.3, near52wHigh: true, volumeSpike: false, tradingValue: 8930 },
    headlines: ["SK Hynix HBM4 mass production on track for Q3", "NVIDIA confirms expanded HBM order with SK Hynix"],
  },
  {
    ticker: "005930",
    name: "Samsung Elec",
    price: 78200,
    chgPct: 1.42,
    tag: "MOMO",
    metrics: { chg1d: 1.42, chg5d: 5.67, chg20d: 9.8, near52wHigh: false, volumeSpike: false, tradingValue: 12400 },
    headlines: ["Samsung secures Qualcomm foundry deal for 2nm GAA", "Foreign investors net buy Samsung for 12th straight session"],
  },
  {
    ticker: "035720",
    name: "Kakao",
    price: 48750,
    chgPct: 1.87,
    tag: "VOLUME SPIKE",
    metrics: { chg1d: 1.87, chg5d: 6.3, chg20d: 2.1, near52wHigh: false, volumeSpike: true, tradingValue: 3870 },
    headlines: ["Kakao AI chatbot user count surpasses 10M", "Kakao Pay regulatory clearance expected this month"],
  },
  {
    ticker: "036570",
    name: "NCsoft",
    price: 198500,
    chgPct: 3.12,
    tag: "MOMO",
    metrics: { chg1d: 3.12, chg5d: 11.4, chg20d: 18.7, near52wHigh: false, volumeSpike: false, tradingValue: 1840 },
    headlines: ["NCsoft Throne & Liberty concurrent users hit new peak", "Analyst upgrades NCsoft to Buy on game pipeline"],
  },
  {
    ticker: "247540",
    name: "Ecopro BM",
    price: 142500,
    chgPct: 4.21,
    tag: "VOLUME SPIKE",
    metrics: { chg1d: 4.21, chg5d: 9.8, chg20d: -5.2, near52wHigh: false, volumeSpike: true, tradingValue: 2680 },
    headlines: ["Ecopro BM signs cathode supply deal with BMW", "Korea battery material stocks rally on EU subsidy news"],
  },
  {
    ticker: "373220",
    name: "LG Energy",
    price: 387000,
    chgPct: 2.15,
    tag: "52W HIGH",
    metrics: { chg1d: 2.15, chg5d: 7.4, chg20d: 12.6, near52wHigh: true, volumeSpike: false, tradingValue: 3210 },
    headlines: ["LG Energy Solution Arizona plant Phase 2 approved", "EV battery demand forecast raised for 2026"],
  },
  {
    ticker: "012330",
    name: "Hyundai Mobis",
    price: 265000,
    chgPct: 1.93,
    tag: "MOMO",
    metrics: { chg1d: 1.93, chg5d: 4.2, chg20d: 8.1, near52wHigh: false, volumeSpike: false, tradingValue: 1560 },
    headlines: ["Hyundai Mobis autonomous driving module wins GM contract"],
  },
  {
    ticker: "035420",
    name: "NAVER",
    price: 224500,
    chgPct: 0.67,
    tag: "MOMO",
    metrics: { chg1d: 0.67, chg5d: 3.8, chg20d: 6.5, near52wHigh: false, volumeSpike: false, tradingValue: 4210 },
    headlines: ["NAVER HyperCLOVA X enterprise adoption accelerates", "NAVER Shopping AI recommendation revenue up 30% QoQ"],
  },
  {
    ticker: "003490",
    name: "Korean Air",
    price: 24650,
    chgPct: 2.76,
    tag: "VOLUME SPIKE",
    metrics: { chg1d: 2.76, chg5d: 8.9, chg20d: 4.3, near52wHigh: false, volumeSpike: true, tradingValue: 980 },
    headlines: ["Korean Air–Asiana merger final EU approval imminent"],
  },
  {
    ticker: "086790",
    name: "Hana Financial",
    price: 62800,
    chgPct: 1.12,
    tag: "52W HIGH",
    metrics: { chg1d: 1.12, chg5d: 3.1, chg20d: 7.8, near52wHigh: true, volumeSpike: false, tradingValue: 870 },
    headlines: ["Korea bank stocks at record on shareholder return push"],
  },
];

export const VALUE_IDEAS: IdeaItem[] = [
  {
    ticker: "006400",
    name: "Samsung SDI",
    price: 412000,
    chgPct: -0.48,
    tag: "PULLBACK",
    metrics: { chg1d: -0.48, chg5d: 1.2, chg20d: -12.4, near52wHigh: false, volumeSpike: false, tradingValue: 2840 },
    headlines: ["Samsung SDI solid-state battery pilot line begins", "Analysts see SDI oversold after 20D decline"],
  },
  {
    ticker: "051910",
    name: "LG Chem",
    price: 368000,
    chgPct: 1.09,
    tag: "PULLBACK",
    metrics: { chg1d: 1.09, chg5d: 2.8, chg20d: -9.7, near52wHigh: false, volumeSpike: false, tradingValue: 3120 },
    headlines: ["LG Chem pharma spin-off valuation catalyzing re-rate", "Institutional buying resumes after 20D pullback"],
  },
  {
    ticker: "068270",
    name: "Celltrion",
    price: 192500,
    chgPct: -1.28,
    tag: "PULLBACK",
    metrics: { chg1d: -1.28, chg5d: 0.4, chg20d: -8.3, near52wHigh: false, volumeSpike: false, tradingValue: 2560 },
    headlines: ["Celltrion biosimilar FDA approval pipeline on track", "Short interest declining as price stabilizes"],
  },
  {
    ticker: "028260",
    name: "Samsung C&T",
    price: 138000,
    chgPct: 0.73,
    tag: "BREAKOUT",
    metrics: { chg1d: 0.73, chg5d: 2.1, chg20d: -3.2, near52wHigh: false, volumeSpike: false, tradingValue: 1450 },
    headlines: ["Samsung C&T governance discount narrowing trend"],
  },
  {
    ticker: "034730",
    name: "SK Inc",
    price: 168500,
    chgPct: 0.30,
    tag: "PULLBACK",
    metrics: { chg1d: 0.3, chg5d: 1.5, chg20d: -11.2, near52wHigh: false, volumeSpike: false, tradingValue: 920 },
    headlines: ["SK Inc NAV discount at widest in 2 years", "SK Group restructuring plan expected in Q2"],
  },
  {
    ticker: "003550",
    name: "LG",
    price: 82300,
    chgPct: -0.36,
    tag: "BREAKOUT",
    metrics: { chg1d: -0.36, chg5d: 0.8, chg20d: -2.1, near52wHigh: false, volumeSpike: false, tradingValue: 680 },
    headlines: ["LG holding company discount expected to compress"],
  },
  {
    ticker: "009150",
    name: "Samsung Electro",
    price: 154000,
    chgPct: 0.98,
    tag: "PULLBACK",
    metrics: { chg1d: 0.98, chg5d: 3.2, chg20d: -7.6, near52wHigh: false, volumeSpike: false, tradingValue: 1280 },
    headlines: ["Samsung Electro-Mechanics MLCC demand recovery seen in H2", "Foreign buying 5 straight days after Q4 miss sell-off"],
  },
  {
    ticker: "105560",
    name: "KB Financial",
    price: 78500,
    chgPct: 0.51,
    tag: "BREAKOUT",
    metrics: { chg1d: 0.51, chg5d: 1.9, chg20d: -1.4, near52wHigh: false, volumeSpike: false, tradingValue: 1640 },
    headlines: ["KB Financial announces record buyback program", "Korea financials low-vol breakout pattern forming"],
  },
];

export const HIGH52_KR: IdeaItem[] = [
  {
    ticker: "000660",
    name: "SK Hynix",
    price: 218000,
    chgPct: 2.84,
    tag: "52W HIGH",
    metrics: { chg1d: 2.84, chg5d: 8.12, chg20d: 14.3, near52wHigh: true, volumeSpike: false, tradingValue: 8930 },
    headlines: ["SK Hynix HBM4 mass production on track for Q3", "NVIDIA confirms expanded HBM order with SK Hynix", "HBM revenue now 50% of SK Hynix total DRAM sales"],
  },
  {
    ticker: "373220",
    name: "LG Energy",
    price: 387000,
    chgPct: 2.15,
    tag: "52W HIGH",
    metrics: { chg1d: 2.15, chg5d: 7.4, chg20d: 12.6, near52wHigh: true, volumeSpike: false, tradingValue: 3210 },
    headlines: ["LG Energy Solution Arizona plant Phase 2 approved", "EV battery demand forecast raised for 2026", "Tesla renews LG Energy cathode supply agreement"],
  },
  {
    ticker: "086790",
    name: "Hana Financial",
    price: 62800,
    chgPct: 1.12,
    tag: "52W HIGH",
    metrics: { chg1d: 1.12, chg5d: 3.1, chg20d: 7.8, near52wHigh: true, volumeSpike: false, tradingValue: 870 },
    headlines: ["Korea bank stocks at record on shareholder return push", "Hana Financial raises dividend payout ratio to 40%", "Foreign ownership of Hana hits 5-year high"],
  },
  {
    ticker: "105560",
    name: "KB Financial",
    price: 78500,
    chgPct: 1.83,
    tag: "52W HIGH",
    metrics: { chg1d: 1.83, chg5d: 4.6, chg20d: 9.2, near52wHigh: true, volumeSpike: false, tradingValue: 1640 },
    headlines: ["KB Financial announces record buyback program", "Korea Value-up index rebalancing adds KB Financial", "KB net profit beats consensus by 8%"],
  },
  {
    ticker: "055550",
    name: "Shinhan FG",
    price: 52400,
    chgPct: 0.96,
    tag: "52W HIGH",
    metrics: { chg1d: 0.96, chg5d: 2.8, chg20d: 6.4, near52wHigh: true, volumeSpike: false, tradingValue: 920 },
    headlines: ["Shinhan Financial total shareholder return tops 7%", "Korea financials rally on corporate governance reforms"],
  },
  {
    ticker: "005930",
    name: "Samsung Elec",
    price: 78200,
    chgPct: 1.42,
    tag: "52W HIGH",
    metrics: { chg1d: 1.42, chg5d: 5.67, chg20d: 9.8, near52wHigh: true, volumeSpike: false, tradingValue: 12400 },
    headlines: ["Samsung secures Qualcomm foundry deal for 2nm GAA", "Foreign net buy Samsung for 12th straight session", "Samsung DRAM pricing power returns in Q1 contracts"],
  },
  {
    ticker: "012330",
    name: "Hyundai Mobis",
    price: 265000,
    chgPct: 1.93,
    tag: "52W HIGH",
    metrics: { chg1d: 1.93, chg5d: 4.2, chg20d: 8.1, near52wHigh: true, volumeSpike: false, tradingValue: 1560 },
    headlines: ["Hyundai Mobis autonomous driving module wins GM contract", "Mobis ADAS revenue up 35% YoY", "Hyundai Group EV platform integration accelerates"],
  },
  {
    ticker: "003670",
    name: "Posco Future M",
    price: 298000,
    chgPct: 3.41,
    tag: "52W HIGH",
    metrics: { chg1d: 3.41, chg5d: 11.2, chg20d: 16.8, near52wHigh: true, volumeSpike: true, tradingValue: 2140 },
    headlines: ["Posco Future M signs long-term nickel supply deal with Vale", "Korea cathode material demand surges on US IRA pull-forward", "Analyst upgrades Posco Future M on margin improvement"],
  },
  {
    ticker: "010130",
    name: "Korea Zinc",
    price: 892000,
    chgPct: 2.28,
    tag: "52W HIGH",
    metrics: { chg1d: 2.28, chg5d: 6.3, chg20d: 10.5, near52wHigh: true, volumeSpike: false, tradingValue: 1320 },
    headlines: ["Korea Zinc copper foil expansion for EV batteries", "Zinc prices at 18-month high on supply disruption", "Korea Zinc governance battle resolved in favor of management"],
  },
  {
    ticker: "035420",
    name: "NAVER",
    price: 224500,
    chgPct: 1.87,
    tag: "52W HIGH",
    metrics: { chg1d: 1.87, chg5d: 5.9, chg20d: 11.3, near52wHigh: true, volumeSpike: false, tradingValue: 4210 },
    headlines: ["NAVER HyperCLOVA X enterprise adoption accelerates", "NAVER Shopping AI recommendation revenue up 30% QoQ", "NAVER Webtoon IPO valuation lifts parent stock"],
  },
  {
    ticker: "066570",
    name: "LG Electronics",
    price: 112000,
    chgPct: 1.54,
    tag: "52W HIGH",
    metrics: { chg1d: 1.54, chg5d: 4.8, chg20d: 8.9, near52wHigh: true, volumeSpike: false, tradingValue: 980 },
    headlines: ["LG Electronics appliance margin hits record high", "LG EV charger business wins major US utility contract"],
  },
  {
    ticker: "096770",
    name: "SK Innovation",
    price: 128500,
    chgPct: 2.67,
    tag: "52W HIGH",
    metrics: { chg1d: 2.67, chg5d: 9.1, chg20d: 13.7, near52wHigh: true, volumeSpike: false, tradingValue: 1870 },
    headlines: ["SK Innovation battery subsidiary SK On turns profitable", "Refining margins widen on seasonal demand uptick", "SK Innovation buyback announcement lifts shares"],
  },
  {
    ticker: "034020",
    name: "Doosan Enerbility",
    price: 21450,
    chgPct: 3.87,
    tag: "52W HIGH",
    metrics: { chg1d: 3.87, chg5d: 12.4, chg20d: 22.1, near52wHigh: true, volumeSpike: true, tradingValue: 2560 },
    headlines: ["Doosan Enerbility wins $2B Czech nuclear plant contract", "Korea nuclear power export pipeline at record high", "Small modular reactor JV with NuScale advances"],
  },
  {
    ticker: "009540",
    name: "HD Korea Shipbldg",
    price: 178000,
    chgPct: 1.76,
    tag: "52W HIGH",
    metrics: { chg1d: 1.76, chg5d: 5.3, chg20d: 9.6, near52wHigh: true, volumeSpike: false, tradingValue: 1430 },
    headlines: ["HD Korea Shipbuilding order book at decade high", "LNG carrier pricing up 15% YoY on strong demand"],
  },
  {
    ticker: "017670",
    name: "SK Telecom",
    price: 58300,
    chgPct: 0.87,
    tag: "52W HIGH",
    metrics: { chg1d: 0.87, chg5d: 2.4, chg20d: 5.8, near52wHigh: true, volumeSpike: false, tradingValue: 640 },
    headlines: ["SK Telecom AI data center revenue doubles YoY", "SKT raises 2026 dividend guidance by 10%"],
  },
];

export const HIGH52_US: IdeaItem[] = [
  {
    ticker: "NVDA",
    name: "NVIDIA",
    price: 142.50,
    chgPct: 3.21,
    tag: "52W HIGH",
    metrics: { chg1d: 3.21, chg5d: 8.7, chg20d: 18.4, near52wHigh: true, volumeSpike: false, tradingValue: 45200 },
    headlines: ["NVIDIA Blackwell B300 shipments ramping ahead of schedule", "Data center revenue beats by $2B on hyperscaler demand", "Jensen Huang: AI inference demand just getting started"],
  },
  {
    ticker: "META",
    name: "Meta Platforms",
    price: 612.30,
    chgPct: 1.87,
    tag: "52W HIGH",
    metrics: { chg1d: 1.87, chg5d: 5.4, chg20d: 12.1, near52wHigh: true, volumeSpike: false, tradingValue: 18900 },
    headlines: ["Meta Llama 4 model tops GPT-4 on key benchmarks", "Reels ad revenue surpasses $20B annual run rate", "Meta Reality Labs losses narrow on Quest 4 pre-orders"],
  },
  {
    ticker: "AAPL",
    name: "Apple",
    price: 238.50,
    chgPct: 0.94,
    tag: "52W HIGH",
    metrics: { chg1d: 0.94, chg5d: 3.2, chg20d: 7.8, near52wHigh: true, volumeSpike: false, tradingValue: 12300 },
    headlines: ["Apple Intelligence driving iPhone 17 upgrade supercycle", "Services revenue hits record $28B quarterly", "Apple Vision Pro 2 launch date confirmed for September"],
  },
  {
    ticker: "AVGO",
    name: "Broadcom",
    price: 228.40,
    chgPct: 2.56,
    tag: "52W HIGH",
    metrics: { chg1d: 2.56, chg5d: 7.8, chg20d: 15.3, near52wHigh: true, volumeSpike: false, tradingValue: 8700 },
    headlines: ["Broadcom AI networking revenue triples YoY", "VMware integration ahead of schedule, raising synergy target", "Custom AI chip deals with 3 additional hyperscalers"],
  },
  {
    ticker: "COST",
    name: "Costco",
    price: 1012.00,
    chgPct: 1.23,
    tag: "52W HIGH",
    metrics: { chg1d: 1.23, chg5d: 3.8, chg20d: 8.2, near52wHigh: true, volumeSpike: false, tradingValue: 4500 },
    headlines: ["Costco same-store sales up 9% beating estimates", "Membership fee increase driving margin expansion", "E-commerce growth accelerates to 22% YoY"],
  },
  {
    ticker: "LLY",
    name: "Eli Lilly",
    price: 892.00,
    chgPct: 2.14,
    tag: "52W HIGH",
    metrics: { chg1d: 2.14, chg5d: 6.1, chg20d: 11.8, near52wHigh: true, volumeSpike: false, tradingValue: 7800 },
    headlines: ["Eli Lilly tirzepatide approved for sleep apnea", "GLP-1 drug demand outstrips supply through 2027", "Lilly raises full-year revenue guidance by $3B"],
  },
  {
    ticker: "NFLX",
    name: "Netflix",
    price: 945.00,
    chgPct: 1.67,
    tag: "52W HIGH",
    metrics: { chg1d: 1.67, chg5d: 4.9, chg20d: 9.4, near52wHigh: true, volumeSpike: false, tradingValue: 5600 },
    headlines: ["Netflix ad tier subscribers surpass 70M globally", "Live sports programming driving engagement records", "Netflix gaming MAU up 3x after GTA integration"],
  },
  {
    ticker: "GE",
    name: "GE Aerospace",
    price: 215.60,
    chgPct: 1.92,
    tag: "52W HIGH",
    metrics: { chg1d: 1.92, chg5d: 5.7, chg20d: 10.3, near52wHigh: true, volumeSpike: false, tradingValue: 3400 },
    headlines: ["GE Aerospace aftermarket revenue surges on fleet age", "LEAP engine deliveries accelerate in Q1", "Defense orders up 20% on increased NATO spending"],
  },
  {
    ticker: "PLTR",
    name: "Palantir",
    price: 98.40,
    chgPct: 4.12,
    tag: "52W HIGH",
    metrics: { chg1d: 4.12, chg5d: 14.3, chg20d: 28.6, near52wHigh: true, volumeSpike: true, tradingValue: 6200 },
    headlines: ["Palantir AIP commercial revenue doubles QoQ", "US Army extends Palantir contract by $480M", "Palantir added to S&P 100 index"],
  },
  {
    ticker: "ANET",
    name: "Arista Networks",
    price: 412.00,
    chgPct: 2.34,
    tag: "52W HIGH",
    metrics: { chg1d: 2.34, chg5d: 8.1, chg20d: 14.7, near52wHigh: true, volumeSpike: false, tradingValue: 2900 },
    headlines: ["Arista 800G switch demand from AI clusters surging", "Cloud titan networking spend up 40% driving orders", "Arista market share gains from Cisco continue in enterprise"],
  },
  {
    ticker: "PANW",
    name: "Palo Alto Networks",
    price: 198.70,
    chgPct: 1.78,
    tag: "52W HIGH",
    metrics: { chg1d: 1.78, chg5d: 5.2, chg20d: 11.1, near52wHigh: true, volumeSpike: false, tradingValue: 3100 },
    headlines: ["Palo Alto platformization strategy driving deal sizes up", "Next-gen security ARR crosses $4.5B milestone", "Federal cybersecurity budget boost benefits Palo Alto"],
  },
  {
    ticker: "UBER",
    name: "Uber Technologies",
    price: 84.20,
    chgPct: 1.45,
    tag: "52W HIGH",
    metrics: { chg1d: 1.45, chg5d: 4.3, chg20d: 9.7, near52wHigh: true, volumeSpike: false, tradingValue: 4100 },
    headlines: ["Uber autonomous vehicle partnerships expand to 5 cities", "Uber Eats ad platform revenue growing 50% YoY", "Uber reaches $10B annual free cash flow milestone"],
  },
];
